services:
  - type: web
    name: recruitment-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn recruitment_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: recruitment_backend.settings
